// ══════════════════════════════════════════════════════════════
// Stage 3 — Hide | Embedding Orchestrator
// ══════════════════════════════════════════════════════════════
//
// Orchestrates the full embedding pipeline by executing Steps 1–5
// in sequence, then updating the UI with results and feature widgets:
//
//   1. Read user inputs (cover-text, secret message, hint, stego-key)
//   2. Build Stego-Payload (Step 1: message + optional hint → bytes)
//   3. Convert Cover-text → Binary (shared/text_codec)
//   4. Validate embedding capacity (payload bits ≤ cover bits)
//   5. Generate PRNG positions (Step 2: stego-key → positions)
//   6. Generate XOR key (Step 3: cover bits ⊕ payload bits)
//   7. Encode via VS Codec (Step 4: XOR key → VS characters)
//   8. Build Stego-Object (Step 5: VS key + cover-text)
//   9. Update feature widgets (visualization, meters, hint log)
//
// Dependencies: step1, step2, step3, step4, step5, shared/text_codec,
//               utils, F_stego_capacity, F_stego_analysis, F_stego_hint
// ══════════════════════════════════════════════════════════════


/**
 * Read and sanitize all user inputs from the embedding panel DOM elements.
 *
 * @returns {{ coverText: string, secretMessage: string, hint: string, stegoKey: string, carrierText: string }}
 */
function readEmbeddingInputs() {
  return {
    coverText: document.getElementById('embedCover').value,
    secretMessage: document.getElementById('embedSecretMessage').value.trim(),
    hint: document.getElementById('embedHint').value.trim(),
    stegoKey: document.getElementById('embedStegoKey').value,
    carrierText: document.getElementById('embedCarrier').value,
  };
}


/**
 * Write embedding results to the DOM output elements.
 *
 * Switches between two output modes:
 *   - Normal mode: single stego-object (cover + VS)
 *   - Split mode:  clean cover (message #1) + carrier with VS (message #2)
 *
 * @param {object} results - The embedding pipeline outputs.
 * @param {number[]} results.basePositions - The PRNG-generated bit positions.
 * @param {string}   results.xorKey        - The binary XOR key.
 * @param {string}   [results.stegoObject] - Normal mode: the completed stego-object.
 * @param {string}   [results.cleanCover]  - Split mode: the clean cover text.
 * @param {string}   [results.carrierWithVS] - Split mode: carrier text with VS prepended.
 * @param {boolean}  results.isSplitMode   - Whether split mode is active.
 */
function displayEmbeddingResults({ basePositions, xorKey, stegoObject, cleanCover, carrierWithVS, isSplitMode }) {
  document.getElementById('baseMapOutput').value =
    '[' + basePositions.join(', ') + ']';
  document.getElementById('shiftKeyOutput').value = xorKey;

  const normalDiv = document.getElementById('outputModeNormal');
  const splitDiv = document.getElementById('outputModeSplit');

  if (isSplitMode) {
    // Split mode: show two separate outputs
    normalDiv.style.display = 'none';
    splitDiv.style.display = 'block';
    document.getElementById('splitCleanCover').value = cleanCover;
    document.getElementById('splitCarrierOutput').value = carrierWithVS;
    // Also populate stegoObject for copyToExtractTab compatibility
    document.getElementById('stegoObject').value = stegoObject || '';
  } else {
    // Normal mode: single stego-object
    normalDiv.style.display = 'block';
    splitDiv.style.display = 'none';
    document.getElementById('stegoObject').value = stegoObject;
  }
}


/**
 * Main embedding pipeline — orchestrates the full embedding process.
 *
 * Supports two output modes based on whether a carrier text is provided:
 *   - No carrier: VS characters are embedded in the cover text (normal)
 *   - With carrier: VS characters are moved to the carrier text (split)
 */
async function performEmbedding() {
  try {
    // ── Read and sanitize inputs
    const { coverText, secretMessage, hint, stegoKey, carrierText } = readEmbeddingInputs();

    // ── Validate required fields
    if (!coverText.trim()) return showToast('⚠ text text text Cover text.');
    if (!secretMessage) return showToast('⚠ text text textmessage text.');

    // ── Validate carrier size (must be >= cover size for plausible deniability)
    const hasCarrier = carrierText.trim().length > 0;
    if (hasCarrier && carrierText.length < coverText.length) {
      showToast(`❌ text Carrier (${carrierText.length} text) text text Cover text (${coverText.length} text). text text text ≥ text Cover text text text text.`);
      return;
    }

    // ── Resolve stego-key (auto-generate from cover-text hash if not provided)
    const { resolvedStegoKey, wasAutoGenerated } = await resolveStegoKey(stegoKey, coverText);
    if (wasAutoGenerated) {
      showToast('🔑 text text text text — text text text text text Cover text (SHA-256).');
    }

    // ── Step 1: Build Stego-Payload (secret message + optional hint → binary)
    const payloadBytes = buildPayload(secretMessage, hint);
    const messageBits = bytesToBinary(payloadBytes);

    // ── shared/text_codec: Cover-text → Binary
    const coverBits = stringToBinary(coverText);

    // ── Embedding capacity validation (payload must fit within cover-text)
    if (messageBits.length > coverBits.length) {
      showToast(`❌ text ${messageBits.length} bits text Cover text text ${coverBits.length} bits text.`);
      return;
    }

    // ── Step 2: Generate PRNG positions (stego-key → seed → positions)
    const basePositions = generatePositions(coverBits.length, messageBits.length, resolvedStegoKey);

    // ── Step 3: Generate XOR key (cover bits ⊕ payload bits at positions)
    const xorKey = generateXORKey(coverBits, basePositions, messageBits);

    // ── Step 4: Encode via VS Codec (XOR key → invisible VS characters)
    const { vsStr, bytesArr } = xorKeyToVSString(xorKey);

    // ── Step 5: Build output based on mode
    if (hasCarrier) {
      // Split mode: VS goes to carrier, cover stays clean
      const carrierWithVS = vsStr + carrierText;
      const stegoObject = buildStegoObject(coverText, vsStr); // for extract tab compatibility

      displayEmbeddingResults({
        basePositions, xorKey,
        stegoObject,
        cleanCover: coverText,
        carrierWithVS,
        isSplitMode: true,
      });

      showToast('✅ text text — Cover text text + text VS text Carrier text!');
    } else {
      // Normal mode: VS embedded in cover
      const stegoObject = buildStegoObject(coverText, vsStr);

      displayEmbeddingResults({
        basePositions, xorKey,
        stegoObject,
        isSplitMode: false,
      });

      showToast('✅ text text text text text Cover text!');
    }

    // ── Feature: VS Visualization (hex breakdown of key bytes)
    updateVSVisualization(xorKey, bytesArr);

    // ── Feature: Key Size Meter (key bytes vs cover characters ratio)
    updateKeySizeMeter(bytesArr.length, coverText.length);

    // ── Feature: Save hint to localStorage (if provided)
    if (hint) {
      saveHint({
        type: 'sent',
        emoji: hint,
        timestamp: new Date().toISOString(),
      });
    }

    // ── Feature: Refresh Embedding Capacity Meter
    updateCapacityMeter();

  } catch (error) {
    showToast('❌ Error text text: ' + error.message);
  }
}

