// ══════════════════════════════════════════════════════════════
// Stage 3 — Hide | Embedding Orchestrator
// ══════════════════════════════════════════════════════════════
//
// Orchestrates the full embedding pipeline by executing Steps 1–4
// in sequence, then updating the UI with results and feature widgets:
//
//   1. Read user inputs (cover-text, secret message, hint, stego-key)
//   2. Build Stego-Payload (Step 2: message + optional hint → bytes)
//   3. Convert Cover-text → Binary (Step 1)
//   4. Validate embedding capacity (payload bits ≤ cover bits)
//   5. Generate Stego-Key (Step 3: positions + XOR)
//   6. Encode via Stego-Channel (Step 4: XOR key → VS characters)
//   7. Build Stego-Object (VS key + cover-text)
//   8. Update feature widgets (visualization, meters, hint log)
//
// Dependencies: step1, step2, step3, step4, utils,
//               F_stego_capacity, F_stego_analysis, F_stego_hint
// ══════════════════════════════════════════════════════════════


/**
 * Read all user inputs from the embedding panel DOM elements.
 *
 * Centralizes DOM access so the orchestrator works with plain data
 * rather than reaching into the DOM directly (SRP).
 *
 * @returns {{ coverText: string, secretMessage: string, hint: string, stegoKey: string }}
 */
function readEmbeddingInputs() {
  return {
    coverText:     document.getElementById('embedCover').value,
    secretMessage: document.getElementById('embedSecretMessage').value,
    hint:          document.getElementById('embedHint').value,
    stegoKey:      document.getElementById('embedStegoKey').value,
  };
}


/**
 * Write embedding results to the DOM output elements.
 *
 * Separates DOM manipulation from business logic so the pipeline
 * can be understood and tested independently.
 *
 * @param {object} results - The embedding pipeline outputs.
 * @param {number[]} results.basePositions - The PRNG-generated bit positions.
 * @param {string}   results.xorKey        - The binary XOR key.
 * @param {string}   results.stegoObject   - The completed stego-object.
 */
function displayEmbeddingResults({ basePositions, xorKey, stegoObject }) {
  document.getElementById('baseMapOutput').value =
    '[' + basePositions.join(', ') + ']';
  document.getElementById('shiftKeyOutput').value = xorKey;
  document.getElementById('stegoObject').value = stegoObject;
}


/**
 * Main embedding pipeline — orchestrates the full embedding process.
 *
 * This is the entry point called by the UI button. It validates inputs,
 * runs the 4-step steganographic embedding pipeline, updates all output
 * fields, and triggers feature widget refreshes.
 */
async function performEmbedding() {
  // ── Read inputs
  const { coverText, secretMessage, hint, stegoKey } = readEmbeddingInputs();

  // ── Validate required fields
  if (!coverText.trim())      return showToast('⚠ الرجاء إدخال النص الغلاف.');
  if (!secretMessage.trim())  return showToast('⚠ الرجاء إدخال الرسالة السرية.');

  // ── Resolve stego-key (auto-generate from cover-text hash if not provided)
  const { resolvedStegoKey, wasAutoGenerated } = await resolveStegoKey(stegoKey, coverText);
  if (wasAutoGenerated) {
    showToast('🔑 لم تُدخل مفتاح إخفاء — تم توليده تلقائياً من هاش الغلاف (SHA-256).');
  }

  // ── Step 2: Build Stego-Payload (secret message + optional hint → binary)
  const payloadBytes = buildPayload(secretMessage, hint);
  const messageBits  = bytesToBinary(payloadBytes);

  // ── Step 1: Cover-text → Binary
  const coverBits = stringToBinary(coverText);

  // ── Embedding capacity validation (payload must fit within cover-text)
  if (messageBits.length > coverBits.length) {
    showToast(`❌ تحتاج ${messageBits.length} بت لكن الغلاف يحتوي ${coverBits.length} بت فقط.`);
    return;
  }

  // ── Step 3: Generate Stego-Key (PRNG positions + XOR comparison)
  const basePositions = generatePositions(coverBits.length, messageBits.length, resolvedStegoKey);
  const xorKey = generateXORKey(coverBits, basePositions, messageBits);

  // ── Step 4: Encode via Stego-Channel (XOR key → invisible VS characters)
  const { vsStr, bytesArr } = xorKeyToVSString(xorKey);

  // ── Build Stego-Object (VS key prepended to cover-text)
  const stegoObject = buildStegoObject(coverText, vsStr);

  // ── Update DOM outputs
  displayEmbeddingResults({ basePositions, xorKey, stegoObject });

  // ── Feature: VS Visualization (hex breakdown of key bytes)
  updateVSVisualization(xorKey, bytesArr);

  // ── Feature: Key Size Meter (key bytes vs cover characters ratio)
  updateKeySizeMeter(bytesArr.length, coverText.length);

  // ── Feature: Save hint to localStorage (if provided)
  if (hint && hint.trim()) {
    saveHint({
      type: 'sent',
      emoji: hint.trim(),
      timestamp: new Date().toISOString(),
    });
  }

  // ── Feature: Refresh Embedding Capacity Meter
  updateCapacityMeter();
  showToast('✅ تم توليد المفتاح وتضمينه في الغلاف!');
}
