// ══════════════════════════════════════════════════════════════
// Stage 3 — Hide | Extraction Orchestrator
// ══════════════════════════════════════════════════════════════
//
// Orchestrates the full extraction (reverse) pipeline by running
// the steps in reverse order (5 → 4 → 2 → 3 → 0 → 1):
//
//   1. Disassemble Stego-Object (Step 5: extract VS bytes + clean text)
//   2. Decode VS bytes → XOR key binary (Step 4: VS → bytes → binary)
//   3. Resolve stego-key (auto-generate from cover-text hash if not provided)
//   4. Convert clean cover-text → binary (shared/text_codec)
//   5. Regenerate same PRNG positions (Step 2: stego-key → positions)
//   6. Recover payload bits via XOR reversal (Step 3: recoverPayloadBits)
//   7. Decompress payload via Brotli Stream (Step 0 reverse: compressed → raw)
//   8. Parse Stego-Payload (Step 1: bytes → secret message + hint)
//   9. Display results in the UI
//
// Dependencies: step1, step2, step3, step4, step5, shared/text_codec,
//               utils, F_stego_hint,
//               stage1_Compress/Wasm_Load_&_Init, stage1_Compress/compression
// ══════════════════════════════════════════════════════════════


/**
 * Display extraction results in the DOM.
 *
 * Shows the recovered secret message, and optionally the hint card
 * with its content. Saves received hints to localStorage.
 *
 * @param {string} secretMessage - The recovered secret message.
 * @param {string} hint          - The recovered hint (empty string if none).
 */
function displayExtractionResults(secretMessage, hint) {
  // Show the secret message card
  document.getElementById('extractResultCard').style.display = 'block';
  document.getElementById('extractedResult').textContent = secretMessage;

  // Show or hide the hint card
  const hintCard = document.getElementById('extractHintCard');

  if (hint) {
    hintCard.style.display = 'block';
    document.getElementById('extractHintEmoji').textContent = hint;
    document.getElementById('extractHintText').textContent = 'الرسالة القادمة ستكون هنا ☝️';

    // Persist received hint to localStorage for the hints tab
    saveHint({
      type: 'received',
      emoji: hint,
      timestamp: new Date().toISOString(),
    });
  } else {
    hintCard.style.display = 'none';
  }
}


/**
 * Main extraction pipeline — recovers the hidden secret message from a stego-object.
 *
 * This is the entry point called by the UI button. It takes the
 * stego-object (cover-text + hidden VS characters) and the stego-key, then
 * reverses the embedding pipeline to recover the original secret message.
 */
async function performExtraction() {
  const stegoObject = document.getElementById('extractCover').value.trim();
  const rawStegoKey = document.getElementById('extractStegoKey').value.trim();

  if (!stegoObject.trim()) return showToast('⚠ Please input the final message.');

  try {
    // ── Step 5 (Reverse): Disassemble Stego-Object — separate VS bytes from visible text
    const { vsBytes, cleanText: coverText } = extractVSFromText(stegoObject);

    if (vsBytes.length === 0) {
      throw new Error('No hidden VS characters found in the message. Make sure to paste the complete final message.');
    }

    // ── Step 4 (Reverse): Decode VS bytes → XOR key binary
    const xorKeyBinary = bytesToBinary(vsBytes);

    // ── Resolve stego-key (DRY — shared with embedding)
    const { resolvedStegoKey, wasAutoGenerated } = await resolveStegoKey(rawStegoKey, coverText);
    if (wasAutoGenerated) {
      showToast('🔑 No stego-key entered — auto-generated from cover hash (SHA-256).');
    }

    // ── shared/text_codec: Cover-text → Binary
    const coverBits = stringToBinary(coverText);

    if (xorKeyBinary.length > coverBits.length) {
      throw new Error(`The key contains ${xorKeyBinary.length} bits but the cover contains only ${coverBits.length} bits.`);
    }

    // ── Step 2 (Reverse): Regenerate the same PRNG positions using the same stego-key
    const basePositions = generatePositions(coverBits.length, xorKeyBinary.length, resolvedStegoKey);

    // ── Step 3 (Reverse): Recover payload bits via XOR reversal
    const recoveredBinary = recoverPayloadBits(coverBits, basePositions, xorKeyBinary);

    // ── Step 0 (Reverse): Check for compression flag and conditionally decompress
    //    If first byte === 0xFE → payload was compressed, strip flag + decompress
    //    If first byte !== 0xFE → payload is raw (was never compressed), use as-is
    const recoveredPayload = binaryToBytes(recoveredBinary);

    let payloadBytes;
    if (recoveredPayload[0] === 0xFE) {
      // Flag 0xFE found → strip it and decompress the rest
      payloadBytes = doStreamDecompress(recoveredPayload.subarray(1));
    } else {
      // No flag → raw payload, no decompression needed
      payloadBytes = recoveredPayload;
    }

    // ── Step 1 (Reverse): Parse Stego-Payload → secret message + hint
    const { secretMessage, hint } = parsePayload(payloadBytes);

    // ── Display results in the UI
    displayExtractionResults(secretMessage, hint);
    showToast('✅ Message extracted successfully!');

  } catch (error) {
    showToast('❌ ' + error.message);
  }
}
