// ══════════════════════════════════════════════════════════════
// Stage 3 — Hide | Extraction Orchestrator
// ══════════════════════════════════════════════════════════════
//
// Orchestrates the full extraction (reverse) pipeline by running
// the steps in reverse order (4 → 3 → 1 → 2):
//
//   1. Decode Stego-Channel (Step 4: extract VS bytes → XOR key binary)
//   2. Separate clean cover text from hidden VS characters
//   3. Resolve password (auto-generate from cover hash if not provided)
//   4. Convert clean cover → binary (Step 1)
//   5. Regenerate same PRNG positions (Step 3: password → positions)
//   6. Recover payload bits via XOR reversal (Step 3: recoverPayloadBits)
//   7. Parse Stego-Payload (Step 2: bytes → secret + hint)
//   8. Display results in the UI
//
// Dependencies: step1, step2, step3, step4, utils, F_stego_hint
// ══════════════════════════════════════════════════════════════


/**
 * Display extraction results in the DOM.
 *
 * Shows the recovered secret message, and optionally the hint card
 * with its content. Saves received hints to localStorage.
 *
 * @param {string} secret - The recovered secret message.
 * @param {string} hint   - The recovered hint (empty string if none).
 */
function displayExtractionResults(secret, hint) {
  // Show the secret message card
  document.getElementById('extractResultCard').style.display = 'block';
  document.getElementById('extractedResult').textContent = secret;

  // Show or hide the hint card
  const hintCard = document.getElementById('extractHintCard');

  if (hint) {
    hintCard.style.display = 'block';
    document.getElementById('extractHintEmoji').textContent = hint;
    document.getElementById('extractHintText').textContent = 'الرسالة القادمة ستكون هنا ☝️';

    // Persist received hint to localStorage for the hints tab
    saveHint({
      type: 'received',
      emoji: hint,
      timestamp: new Date().toISOString(),
    });
  } else {
    hintCard.style.display = 'none';
  }
}


/**
 * Main extraction pipeline — recovers the hidden message from a stego-object.
 *
 * This is the entry point called by the UI button. It takes the final
 * stego-object (cover + hidden VS characters) and the password, then
 * reverses the embedding pipeline to recover the original secret.
 */
async function extractSecretMessage() {
  const finalMessage = document.getElementById('extractCover').value;
  const rawPassword  = document.getElementById('extractPassword').value;

  if (!finalMessage.trim()) return showToast('⚠ الرجاء إدخال الرسالة النهائية.');

  try {
    // ── Step 4 (Reverse): Decode Stego-Channel — separate VS bytes from visible text
    const { vsBytes, cleanText: coverText } = extractVSFromText(finalMessage);

    if (vsBytes.length === 0) {
      throw new Error('لا توجد أحرف مخفية (VS) في الرسالة. تأكد من لصق الرسالة النهائية كاملة.');
    }

    // Reconstruct binary XOR key from extracted VS bytes
    const xorKeyBinary = bytesToBinary(vsBytes);

    // ── Resolve password (DRY — shared with embedding)
    const { resolvedPassword, wasAutoGenerated } = await resolvePassword(rawPassword, coverText);
    if (wasAutoGenerated) {
      showToast('🔑 لم تُدخل كلمة مرور — تم توليدها تلقائياً من هاش الغلاف (SHA-256).');
    }

    // ── Step 1: Cover → Binary
    const coverBits = stringToBinary(coverText);

    if (xorKeyBinary.length > coverBits.length) {
      throw new Error(`المفتاح يحتوي ${xorKeyBinary.length} بت لكن الغلاف يحتوي ${coverBits.length} بت فقط.`);
    }

    // ── Step 3: Regenerate the same PRNG positions using the same password
    const basePositions = generatePositions(coverBits.length, xorKeyBinary.length, resolvedPassword);

    // ── Step 3 (cont.): Recover payload bits via XOR reversal
    //    Uses the shared recoverPayloadBits() instead of duplicating the XOR loop
    const recoveredBinary = recoverPayloadBits(coverBits, basePositions, xorKeyBinary);

    // ── Step 2: Parse Stego-Payload → secret + hint
    const payloadBytes = binaryToBytes(recoveredBinary);
    const { secret, hint } = parsePayload(payloadBytes);

    // ── Display results in the UI
    displayExtractionResults(secret, hint);
    showToast('✅ تم استخراج الرسالة بنجاح!');

  } catch (error) {
    showToast('❌ ' + error.message);
  }
}
